### ISSUE TITLE
IllegalArgumentException causing build failure

### ISSUE THREAD

**Issue by Kevinwlee** [evernote/android-state#11]
I'm getting `java.lang.IllegalArgumentException: expected name but was null`  when using android-state with Kotlin.

I have this class

```kotlin
class YNABFormats(val context: Context) {
    class Currency(val default_locale: String, val iso_code: String, val english_name: String) : Serializable {
        override fun toString(): String {
            return "$english_name - $iso_code"
        }
    }
}
```

I have this in my fragment:
```kotlin
    @State var selectedCurrency: YNABFormats.Currency? = null
```

build.gradle
```gradle
    compile 'com.evernote:android-state:1.0.5'
    kapt 'com.evernote:android-state-processor:1.0.5'
```

When I compile the application I get the following error:
```
Caused by: java.lang.IllegalArgumentException: expected name but was null
	at com.squareup.javapoet.CodeBlock$Builder.argToName(CodeBlock.java:209)
	at com.squareup.javapoet.CodeBlock$Builder.add(CodeBlock.java:167)
	at com.squareup.javapoet.CodeBlock$Builder.addStatement(CodeBlock.java:267)
	at com.squareup.javapoet.MethodSpec$Builder.addStatement(MethodSpec.java:465)
	at com.evernote.android.state.StateProcessor.process(StateProcessor.java:299)
	at org.jetbrains.kotlin.annotation.AnnotationProcessorWrapper.process(AnnotationProcessorWrapper.kt:129)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	... 98 more
```

I am able to build successfully when I remove `@State` from the field.

**Comment by vRallev** [comment]
I can reproduce the issue with the snippets. Seems like there's a problem with the inner class. If I remove the outer class, then it's working fine.

**Comment by vRallev** [comment]
I've uploaded a snapshot build with a fix. Could you give it a try and let me know if that works?
```groovy
repositories {
    jcenter()

    maven {
        url 'https://oss.sonatype.org/content/repositories/snapshots/'
    }
}

dependencies {
    compile 'com.evernote:android-state:1.0.6-SNAPSHOT'
    kapt 'com.evernote:android-state-processor:1.0.6-SNAPSHOT'
}
```

**Comment by Kevinwlee** [comment]
`BUILD SUCCESSFUL`
That seems to have fixed it!

**Comment by vRallev** [comment]
Nice! You can keep using the snapshot build. I'll probably release 1.0.6 next week.

**Comment by Kevinwlee** [comment]
Sounds great!  Thanks for fixing it so quickly.
